title: Institute for Qur’anic Content
url: https://IQC.oarc.science
description: A Qur’anic society adhering to Open Access values


assets:
    - name: Multilingual Qur’an Reader
      url:  read.iqc.oarc.science
      buttonp1: Read · iqc
      buttonp2: .oarc.science
      description: This engine hosts several Open Access Qur’an translations.
      github: github.com/oarcscience/read.iqc.oarc.science
    - name: Intangible Textual Heritage
      url:  ith.oarc.science
      buttonp1: Intangible
      buttonp2: Textual Heritage<br>ith.oarc.science
      description: Intangible Textual Heritage is an Open Access archive of quintessential texts of our civilization. IQC contributes to its Islam- and Qur’an-related sections.
      github: github.com/oarcscience/ith.oarc.science